import 'landmark.dart';

final Map<String, Landmark> building1Landmarks = {
  // A=2 (Room) in id ABC
  'room_a': Landmark(
    id: '201', // A=2 (room), BC=01
    name: 'Storage Room A',
    property: '3x3',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: 7.5,
  ),
  'room_b': Landmark(
    id: '202',
    name: 'Storage Room B',
    property: '3x3',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: 3.5,
  ),
  'room_c': Landmark(
    id: '203',
    name: 'Office C',
    property: '4x4',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 9.0,
    y: 4.0,
  ),
  'room_d': Landmark(
    id: '204',
    name: 'Office D',
    property: '4x4',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 14.0,
    y: 4.0,
  ),
  'room_e': Landmark(
    id: '205',
    name: 'Restroom E',
    property: '3x6',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: -5.0,
  ),
  'room_f': Landmark(
    id: '206',
    name: 'Function Room F',
    property: '9x5',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 11.5,
    y: -4.5,
  ),

  // A=3 (landmark) in id ABC
  'stairs_g': Landmark(
    id: '301', // A=3 (multi-level access), BC=01
    name: 'Stairway G',
    property: '3x6',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 10.0,
    y: -12.5,
  ),
  'elevator_h': Landmark(
    id: '302',
    name: 'Elevator H',
    property: '2x2',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 15.0,
    y: -2.0,
  ),
  'plant_elevator': Landmark(
    id: '303',
    name: 'plant in brown basket',
    property: 'tall, green',
    type: 'plant',
    sensoryType: 'visual',
    isNode: false,
    x: 13,
    y: -9.8,
  ),
  'board_function_room': Landmark(
    id: '304',
    name: 'Research News Board',
    property: 'brown, wooden',
    type: 'bulletitin board',
    sensoryType: 'visual',
    isNode: false,
    x: 5.9,
    y: -7,
  ),
  'fountain_restroom': Landmark(
    id: '305',
    name: 'drink fountain',
    property: 'rectangular',
    type: 'drink fountain',
    sensoryType: 'visual',
    isNode: false,
    x: 4,
    y: -1,
  ),
  'painting_office_storage': Landmark(
    id: '306',
    name: 'painting',
    property: 'vibrant, patterned',
    type: 'display',
    sensoryType: 'visual',
    isNode: false,
    x: 6,
    y: 4.5,
  ),
  'chair_corner_storage': Landmark(
    id: '307',
    name: 'chair',
    property: 'red, soft',
    type: 'chair',
    sensoryType: 'visual',
    isNode: false,
    x: 4.5,
    y: 8.5,
  ),

  // A=1 (nodes) in id ABC
  'start': Landmark(
    id: '100',
    name: 'start',
    property: '',
    type: '',
    sensoryType: '',
    isNode: true,
    x: 0,
    y: 0,
  ),
  'corner_4_9': Landmark(
    id: '101', // A=1 (node), BC=01 (first node excluding the reference point)
    name: 'corner',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 4.0,
    y: 9.0,
  ),
  'junc_5_0': Landmark(
    id: '102',
    name: '4-way intersection',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 5.0,
    y: 0.0,
  ),
  'junc_5_neg9': Landmark(
    id: '103',
    name: 'T-junction',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 5.0,
    y: -9.0,
  ),
  'node_5_3p5': Landmark(
    id: '104',
    name: 'to Storage Room B',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 5.0,
    y: 3.5,
  ),
  'node_11p5_8': Landmark(
    id: '105',
    name: 'bisector behind Room C and D',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 11.5,
    y: 8,
  ),
  'node_9p5_0': Landmark(
    id: '106',
    name: 'to Office C',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 9.5,
    y: 0,
  ),
  'node_14p5_0': Landmark(
    id: '107',
    name: 'to Office D',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 14.5,
    y: 0,
  ),
  'node_5_neg3p5': Landmark(
    id: '108',
    name: 'to Restroom E',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 5,
    y: -3.5,
  ),
  'node_7p5_neg9': Landmark(
    id: '109',
    name: 'to Stairway G',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 7.5,
    y: -9,
  ),
  'node_15_neg9': Landmark(
    id: '110',
    name: 'to Elevator H',
    property: '',
    type: 'node',
    sensoryType: '',
    isNode: true,
    x: 15,
    y: -9,
  ),
};
