import 'landmark.dart';

final Map<String, Landmark> building1Landmarks = {
  'Start': Landmark(
    id: '0',
    name: 'Reference Point',
    property: '',
    type: '',
    sensoryType: '',
    isNode: false,
    x: 0,
    y: 0, 
  ),
  'Storage Room A' : Landmark(
    id: 'A',
    name: 'Storage Room A',
    property: '3x3',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: 7.5, 
  ),
  'Storage Room B': Landmark(
    id: 'B',
    name: 'Storage Room B',
    property: '3x3',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: 3.5,
  ),
  'Office C': Landmark(
    id: 'C',
    name: 'Office C',
    property: '4x4',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 9.0,
    y: 4.0,
  ),
  'Office D': Landmark(
    id: 'D',
    name: 'Office D',
    property: '4x4',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 14.0,
    y: 4.0,
  ),
  'Restroom E': Landmark(
    id: 'E',
    name: 'Restroom E',
    property: '3x6',
    type: 'room',
    sensoryType: 'visual',
    isNode: false,
    x: 1.5,
    y: -5.0,
  ),
  'Function Room F': Landmark(
    id: 'F',
    name: 'Function Room F',
    property: '9x5',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 11.5,
    y: -4.5,
  ),
  'Stairway G': Landmark(
    id: 'G',
    name: 'Stairway G',
    property: '3x6',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 10.0,
    y: -12.5,
  ),
  'Elevator H': Landmark(
    id: 'H',
    name: 'Elevator H',
    property: '2x2',
    type: 'room',
    sensoryType: '',
    isNode: false,
    x: 15.0,
    y: -2.0,
  ),
  'Corner': Landmark(
    id: 'J1',
    name: 'corner',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 4.0,
    y: 9.0,
  ),
  '4-way Intersection': Landmark(
    id: 'J2',
    name: '4-way intersection',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 5.0,
    y: 0.0,
  ),
  'T-Junction': Landmark(
    id: 'J3',
    name: 'T-junction',
    property: '',
    type: 'junction',
    sensoryType: 'visual',
    isNode: true,
    x: 5.0,
    y: -9.0,
  ),
  'Plant': Landmark(
    id: 'l1',
    name: 'plant in brown basket',
    property: 'tall, green',
    type: 'plant',
    sensoryType: 'visual',
    isNode: false,
    x: 13,
    y: -9.8,
  ),
  'Board': Landmark(
    id: 'l2',
    name: 'Research News Board',
    property: 'brown, wooden',
    type: 'bulletitin board',
    sensoryType: 'visual',
    isNode: false,
    x: 5.9,
    y: -7,
  ),
  'Fountain': Landmark(
    id: 'l3',
    name: 'drink fountain',
    property: 'rectangular',
    type: 'drink fountain',
    sensoryType: 'visual',
    isNode: false,
    x: 4,
    y: -1,
  ),
  //
  'Painting': Landmark(
    id: 'l4',
    name: 'painting',
    property: 'vibrant, patterned',
    type: 'display',
    sensoryType: 'visual',
    isNode: false,
    x: 6,
    y: 4.5,
  ),
  'Chair': Landmark(
    id: 'l5',
    name: 'chair',
    property: 'red, soft',
    type: 'chair',
    sensoryType: 'visual',
    isNode: false,
    x: 4.5,
    y: -0.9,
  ),
};
